### ISSUE TITLE
Support for CSR

### ISSUE THREAD

**Issue by hossein1387** [mortbopet/Ripes#106]
It seems Ripes does not support CSR instructions. I was wondering if this is correct and if it is, any plan to add CSRs?

**Comment by mortbopet** [comment]
Correct, the Zicsr ISA extension is not yet implemented.
I'd hope for there to be support for the F (and D, for 64-bit) extension in the future, which would imply supporting Zicsr. However, It's probably not a feature that will be available in the short run, since I'll soon have quite a bit of work to attend to... however, I'm always happy to give my input on PRs!.
