### ISSUE TITLE
Ripes crashes when using 'Open' Syscall

### ISSUE THREAD

**Issue by lasnikr** [mortbopet/Ripes#326]
Ripes crashes when using 'Open' Syscall:
```
li a7, 1024
ecall
```
This happens with and without arguments and with and without the file actually being present in my testing
I am on Mac and on the newest commit (built myself) but I also tried some older commits and saw the same bug. I can't try with the latest release because it is broken on Mac.

**Comment by raccog** [comment]
@lasnikr This seems to be fixed by #325, which should be pushed to the main branch soon.

#325 makes it so that (instead of crashing) ecall will return `-1` to the `a0` register, showing that it failed.

I'll keep this issue open until the PR is accepted into the main branch, so we can be sure that it fixes the bug.

**Comment by raccog** [comment]
@mortbopet This issue should be closed; the provided example does not crash anymore on the main branch. It was fixed by #325.
